### PR TITLE
Typecheck with constructor for performance

### PR DESCRIPTION
**Pull request by bsiddiqui**
This way is about 5x faster: http://jsperf.com/instanceof-array-vs-array-isarray

### CODE REVIEW

**Comment by bendrucker** [comment]
I'm cool with --readability for ++perf for this but it needs to behave identically. Specifically it needs to handle non-object values where accessing `value.constructor` would throw. Would like to see direct benchmarks between that and `Array.isArray`.

**Comment by bsiddiqui** [comment]
Yeah significantly faster for arrays but looks like it is slower for non-array values

**Comment by bendrucker** [comment]
That's not what I'm thinking of though. The `Array.isArray` approach handles `null` and `undefined`.

**Comment by bsiddiqui** [comment]
Ah so you're saying you'd have to do something like `(value && value.constructor) === Array` to get the same behavior?

**Comment by bendrucker** [comment]
Correct. Should still be faster, but that's the only fair test. You'd need to add tests against those values. And then there's the fact that you can pass in `{constructor: Array}`. Somewhat contrived, but so is squeezing performance out of a lib like this. I'm using it to allow you to pass an array of strings or a string itself as an arg, but for a code path that's called fairly infrequently.

**Comment by bsiddiqui** [comment]
Yeah makes sense and given you have to check that I see what you mean about readability

http://jsperf.com/instanceof-array-vs-array-isarray/23
screenshot 2015-09-04 22 24 19

**Comment by bendrucker** [comment]
So in the case where the input isn't an array, the constructor approach is slower. In that case I really don't think micro-perf optimization makes sense. Using the native fn is often faster and is spec-compliant.

**Comment by bsiddiqui** [comment]
:+1:

**Pull request closed without merging**
